name: kraken-benchmark
channels:
  - districtdatalabs
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  # from Kraken
  - python>=3.6
  - python-bidi
  - lxml
  - future
  - regex
  - requests
  - click>=7.0
  - numpy
  - pillow>=6.2.2
  - scipy
  - protobuf>=3.0
  - jinja2
  - torchvision>=0.5.0
  - cpuonly
  - pytorch==1.5.0
  - jsonschema
  - scikit-image
  - shapely
  - pip
  - pyvips
  - imagemagick<7.0.9
  # for Kraken Benchmark specifically
  - tqdm==4.46.1
  - pyfiglet==0.08.post1
  - Flask==1.1.2
  - termcolor==1.1.0
  - prompt-toolkit==3.0.5
  - nltk==3.5
  - python-levenshtein=0.12.0
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - pandas=1.0.3
  - scikit-learn=0.22.1
  - scikit-plot=0.3.7
  - scipy=1.4.1
  - seaborn=0.10.1
  - pylint=2.4.4
  - pydocstyle=4.0.1
  - pyflakes=2.1.1
  - notebook
  - pip:
    - coremltools>=3.3
    - git+https://github.com/mittagessen/kraken.git@master